"""Create pokemon table

Revision ID: 6828a0d133da
Revises: 
Create Date: 2023-03-09 11:15:25.321343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6828a0d133da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('imageURL', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('moves', sa.String(length=255), nullable=False),
    sa.Column('encouterRate', sa.Float(precision=3, asdecimal=2), nullable=False),
    sa.Column('catchRate', sa.Float(precision=3, asdecimal=2), nullable=False),
    sa.Column('captured', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemons')
    # ### end Alembic commands ###
